    steps:
      - name: Checkout code
        # آپدیت به آخرین نسخه پایدار
        uses: actions/checkout@v4

      - name: Set up Python
        # آپدیت به آخرین نسخه پایدار
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # پیشنهاد می‌شود از یک نسخه جدیدتر پایتون استفاده کنی

      - name: Run Python script
        run: |
          python test1.py
